language: python

jobs:
  include:
  - language: python
    python: 2.7
    install:
    - pip install -r backend/requirements.txt
    script:
    - pytest -v backend/*_test.py
    flask:
    -python -m flask run
  - language: node_js
    node_js: 12
    install:
    - npm install
    before_deploy:
    - cd frontend
    script:
    - npm run build

